# Generated by Django 3.1.6 on 2021-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrakenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Record Title')),
                ('file', models.FileField(upload_to='records/', verbose_name='Record File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation')),
            ],
        ),
    ]
