# Generated by Django 3.1.6 on 2021-02-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemember',
            name='contact_url',
            field=models.URLField(blank=True, verbose_name='Contact Url'),
        ),
        migrations.AlterField(
            model_name='sitemember',
            name='about',
            field=models.TextField(blank=True, verbose_name='About Yourself'),
        ),
    ]
